name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: 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
          OPENAI_API_KEY: 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
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false